spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # 콘솔에 남김
        # show_sql: true
        format_sql: true

  # paging 글로벌 설정
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        # 페이지 첫 인덱스 1 처리 - 문제가 있음
        # page 데이터가 안맞음.
#        one-indexed-parameters: true



logging.level:
  # 로그파일로 남김
  org.hibernate.SQL: debug
  # 파라미터 확인
#  org.hibernate.type: trace
